In [219]:
import numpy as np
from numpy.linalg import norm
from math import sin, cos, pi, asin, atan2, degrees
from tabulate import tabulate

np.set_printoptions(suppress=True,precision=11)

In [204]:
def wedge(v):
    return np.matrix([[0, -v[2], v[1]],
                     [v[2], 0,  -v[0]],
                     [-v[1], v[0], 0]]);

def get_rotation_rodriguez(v, theta=None):
    if theta is None:
        theta = norm(v); 
        n = v/theta; 
    else: 
        n = v; 
        
    cM = wedge(n); 
    return np.identity(3) + sin(theta)*cM + (1-cos(theta))*cM*cM

def rotx(phi):
    v = phi*np.array([1, 0, 0]); 
    return get_rotation_rodriguez(v)

def roty(theta):
    v = theta*np.array([0, 1, 0]); 
    return get_rotation_rodriguez(v)

def rotz(psi):
    v = psi*np.array([0, 0, 1]); 
    return get_rotation_rodriguez(v) 

def angles2rot(phi, theta, psi): 
    return rotz(psi)*roty(theta)*rotx(phi)

def rot2angles(M):
    sin_theta = -M[2, 0];     
    theta = asin(sin_theta);     
    
    if sin_theta==1:
        psi = 0; # arbitrary
        phi = atan2(M[0,1],M[0,2]);     
    elif sin_theta==-1:
        psi = 0; # arbitrary
        phi = atan2(-M[0,1],-M[0,2]);        
    else:
        # another valid solution: pi-theta.             
        cos_theta = cos(theta); 
        phi = atan2(M[2,1]/cos_theta, M[2, 2]/cos_theta);
        psi = atan2(M[1,0]/cos_theta, M[0, 0]/cos_theta);
    
    return phi, theta, psi
    
def rigid_transform3(trans, rot): 
    M = np.identity(4)
    M[0:3,0:3] = rot
    M[0:3,3] = trans
    return M
#    return np.concatenate((np.concatenate((rot, trans), axis=1), 
#                           np.concatenate((np.zeros((1, 3)), np.mat([[1]])), axis=1)), axis=0)

In [139]:
# print('rotx=')
# print(rotx(pi/2))
# print(3*'\n' + 'roty=')
# print(roty(pi/2))
# print(3*'\n' + 'rotz=')
# print(rotz(pi/2))

print('phi,theta,psi = ' + str([pi/4, pi/5, pi/7]))
print('\nangles2rot: \n' + str(angles2rot(phi=pi/4, theta=pi/5, psi=pi/7)))
print('\nrot2angles: \n' + str(rot2angles(angles2rot(phi=pi/4, theta=pi/5, psi=pi/7))))
phi, theta, psi = rot2angles(angles2rot(phi=pi/4, theta=pi/5, psi=pi/7))
#print(angles2rot(phi, theta, psi))
#print(rot2angles(angles2rot(phi, theta, psi)))
#print(angles2rot(phi, theta, psi))


phi,theta,psi = [0.7853981633974483, 0.6283185307179586, 0.4487989505128276]

angles2rot: 
[[ 0.72889912554  0.06766479742  0.68126906578]
 [ 0.35101931853  0.81741496597 -0.45674742629]
 [-0.58778525229  0.57206140282  0.57206140282]]

rot2angles: 
(0.7853981633974483, 0.6283185307179586, 0.4487989505128276)


In [159]:
phi, theta, psi = (degrees(x) for x in rot2angles(
    np.mat(' 0.813797681 -0.440969611 0.378522306;  \
                           0.46984631   0.882564119 0.0180283112; \
                          -0.342020143  0.163175911 0.925416578')))
print(phi, theta, psi)

9.999999994217536 19.999999980143038 29.99999998990158


In [221]:
trans = np.mat([-451.2459, 257.0322, 400])
rot = np.mat('0.5363 -0.8440 0; 0.8440 0.5363 0; 0 0 1'); 

pt = [450, 400, 50, 1]

print(trans)
print(rot)

Tgl = rigid_transform3(-trans, rot.transpose()); 
print(Tgl.dot(pt))
#print(tabulate(Tgl, tablefmt="latex", floatfmt=".2f"))
print(tabulate(Tgl, tablefmt="latex"))

[[-451.2459  257.0322  400.    ]]
[[ 0.5363 -0.844   0.    ]
 [ 0.844   0.5363  0.    ]
 [ 0.      0.      1.    ]]
[ 1030.1809  -422.3122  -350.         1.    ]
\begin{tabular}{rrrr}
\hline
  0.5363 & 0.844  & 0 &  451.246 \\
 -0.844  & 0.5363 & 0 & -257.032 \\
  0      & 0      & 1 & -400     \\
  0      & 0      & 0 &    1     \\
\hline
\end{tabular}
